# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JJAppUpdateDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JJAppUpdateSDK', :path =>'./JJAppUpdateSDK'

  pod 'Masonry', '1.1.0'
  pod 'Toast'
  # pod 'Protobuf'

  target 'JJAppUpdateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JJAppUpdateDemoUITests' do
    # Pods for testing
  end

end
